//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_UpgradeInput : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean LIndexBool
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LIndexBool;
            }
        }
        
        public virtual SteamVR_Action_Boolean LIndexTouch
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LIndexTouch;
            }
        }
        
        public virtual SteamVR_Action_Single LIndexPress
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LIndexPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean LMiddleBool
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LMiddleBool;
            }
        }
        
        public virtual SteamVR_Action_Boolean LMiddleTouch
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LMiddleTouch;
            }
        }
        
        public virtual SteamVR_Action_Single LMiddlePress
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LMiddlePress;
            }
        }
        
        public virtual SteamVR_Action_Boolean LThumbX
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LThumbX;
            }
        }
        
        public virtual SteamVR_Action_Boolean LThumbXRest
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LThumbXRest;
            }
        }
        
        public virtual SteamVR_Action_Boolean LThumbY
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LThumbY;
            }
        }
        
        public virtual SteamVR_Action_Boolean LThumbYRest
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LThumbYRest;
            }
        }
        
        public virtual SteamVR_Action_Boolean LThumbMenu
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LThumbMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean LThumbMenuRest
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LThumbMenuRest;
            }
        }
        
        public virtual SteamVR_Action_Vector2 LThumbAnal
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LThumbAnal;
            }
        }
        
        public virtual SteamVR_Action_Boolean LThumbAnalPress
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LThumbAnalPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean LThumbAnalRest
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LThumbAnalRest;
            }
        }
        
        public virtual SteamVR_Action_Boolean RIndexBool
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RIndexBool;
            }
        }
        
        public virtual SteamVR_Action_Boolean RIndexTouch
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RIndexTouch;
            }
        }
        
        public virtual SteamVR_Action_Single RIndexPress
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RIndexPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean RMiddleBool
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RMiddleBool;
            }
        }
        
        public virtual SteamVR_Action_Boolean RMiddleTouch
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RMiddleTouch;
            }
        }
        
        public virtual SteamVR_Action_Single RMiddlePress
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RMiddlePress;
            }
        }
        
        public virtual SteamVR_Action_Boolean RThumbA
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RThumbA;
            }
        }
        
        public virtual SteamVR_Action_Boolean RThumbARest
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RThumbARest;
            }
        }
        
        public virtual SteamVR_Action_Boolean RThumbB
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RThumbB;
            }
        }
        
        public virtual SteamVR_Action_Boolean RThumbBRest
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RThumbBRest;
            }
        }
        
        public virtual SteamVR_Action_Boolean RThumbMenu
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RThumbMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean RThumbMenuRest
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RThumbMenuRest;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RThumbAnal
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RThumbAnal;
            }
        }
        
        public virtual SteamVR_Action_Boolean RThumbAnalPress
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RThumbAnalPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean RThumbAnalRest
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RThumbAnalRest;
            }
        }
        
        public virtual SteamVR_Action_Vibration LShake
        {
            get
            {
                return SteamVR_Actions.upgradeInput_LShake;
            }
        }
        
        public virtual SteamVR_Action_Vibration RShake
        {
            get
            {
                return SteamVR_Actions.upgradeInput_RShake;
            }
        }
    }
}
